name: Validate JSON

on:
  pull_request:
    branches:
      - "**"

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate JSON files
        uses: OrRosenblatt/validate-json-action@v1
        with:
          json-schema: false
          files: "**/*.json"